name: Objective:(Option 2)

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      run_tests:
        description: 'Set to true if you want to run tests'
        required: true
        default: 'true'
        type: boolean

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18' 

      - name: Install dependencies
        run: npm run DependencyInstall

      - name: Run tests
        run: npm run cucumber 

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: ./BackendReport
